evan_airlines/Models/ErrorViewModel.cs
namespace evan_airlines.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

evan_airlines/Controllers/CheckoutController.cs
using evan_airlines.Interfaces;
using evan_airlines.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Cosmos;
using Microsoft.EntityFrameworkCore;
using System;

namespace evan_airlines.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly AppDbContext context;
        public CheckoutController(AppDbContext _context)
        {
            context = _context;
        }

        public IActionResult Index(string user)
        {
            var cart = context.Checkout
                .Where(entry => entry.User == user)
                .ToList();
            return View(cart);
        }

        public string generateConfirmationCode()
        {
            string confirmation = "";
            for (int i = 0; i < 5; i++)
            {
                Random random = new Random();
                char c = (char)random.Next('A', 'Z' + 1);
                confirmation += c;
            }
            return confirmation;
        }

        [HttpPost]
        public IActionResult ThankYou(CheckoutModel checkout, string firstName, string lastName)
        {

            string confirmationCode = generateConfirmationCode();
            var entriesToRemove = context.Checkout.Where(entry => entry.User == checkout.User).ToList();
            if (firstName == null || lastName == null || entriesToRemove.Count == 0)
            {
                throw new ApplicationException("XDDCC");
            }
            foreach (var entry in entriesToRemove)
            {
                ConfirmationModel confirmation = new ConfirmationModel
                {
                    ConfirmationCode = confirmationCode,
                    FirstName = firstName,
                    LastName = lastName,
                    Route = entry.Departure + " - " + entry.Arrival,
                    Number = entry.Number
                };
                context.Confirmation.Add(confirmation);
            }

            context.Checkout.RemoveRange(entriesToRemove);
            context.SaveChanges();

            // Now, retrieve confirmations for the specific confirmationCode
            var confirmations = context.Confirmation
                .Where(entry => entry.ConfirmationCode == confirmationCode)
                .ToList();

            return View(confirmations);
        }
    }
}

evan_airlines/Controllers/EmployeesController.cs
using evan_airlines.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace evan_airlines.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly AppDbContext context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EmployeesController(AppDbContext _context, IWebHostEnvironment _webHostEnvironment) 
        {
            context = _context;
            webHostEnvironment = _webHostEnvironment;
        }
        public IActionResult Index()
        {
            var employees = context.Employees.ToList();
            return View(employees);
        }

        public IActionResult Detail(int id)
        {
            EmployeeModel employee = context.Employees.FirstOrDefault(e => e.id == id);
            return View(employee);
        }
    }
}

evan_airlines/Controllers/FlightsController.cs
using evan_airlines.Interfaces;
using evan_airlines.Models;
using Microsoft.AspNetCore.Mvc;

namespace evan_airlines.Controllers
{
    public class FlightsController : Controller
    {
        private readonly AppDbContext context;
        private readonly FlightService flightService;

        public FlightsController(AppDbContext _context, IWebHostEnvironment _webHostEnvironment, FlightService _flightService)
        {
            context = _context;
            flightService = _flightService;
        }
        public IActionResult Index()
        {
            var flights = flightService.GetAllFlights();
            return View(flights);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(string departure, string arrival)
        {
            // Filter flights based on departure and arrival
            var filteredFlights = flightService.SearchFlights(departure, arrival);

            // Return a partial view with the filtered flights
            return View(filteredFlights);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddToCart(FlightModel flight, string user)
        {
            CheckoutModel entry = new CheckoutModel
            {
                User = user,
                Departure = flight.departure,
                Arrival = flight.arrival,
                Number = flight.number,
                Cost = flight.cost,
            };
            try
            {
                context.Checkout.Add(entry);
                context.SaveChanges();
                ViewBag.AddToCartMessage = "Flight added to cart!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                ViewBag.AddToCartMessage = "Error adding flight to cart";
                return RedirectToAction("Index");
            }
        }
    }
}

evan_airlines/Controllers/LogbookController.cs
using evan_airlines.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace evan_airlines.Controllers
{
    public class LogbookController : Controller
    {
        private readonly AppDbContext context;
        public LogbookController(AppDbContext _context)
        {
            context = _context;
        }

        public IActionResult Index()
        {
            var flights = context.Logbook.ToList();
            return View(flights);
        }

        public IActionResult Flown(string name)
        {
            var filteredFlights = context.Logbook.Where(flight => flight.pilot == name || flight.copilot == name || flight.fa_1 == name || flight.fa_2 == name).ToList();                
            return View(filteredFlights); // Pass the filtered flights to the view
        }
    }
}

evan_airlines/Views/Shared/_Error.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Error</title>
</head>
<body>
    <div class="px-4 py-5 my-5 text-center">
        <img class="d-block mx-auto mb-4" src="~/Images/error.jpg" alt="Sad Evan" height="350">
        <h1 class="text-danger" class="display-5 fw-bold text-body-emphasis">An Error occurred</h1>
        <div class="col-lg-6 mx-auto">
            <p style="font-size: 36px">
                @ViewData["ErrorMessage"]
            </p>
        </div>
    </div>
</body>
</html>

evan_airlines/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Evan Airlines</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/evan_airlines.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow" style="background-color: lightblue">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home">Evan Airlines</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" style="border-right: 1px solid #000">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item" style="border-right: 1px solid #000">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item" style="border-right: 1px solid #000">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Logbook" asp-action="Index">Logbook</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flights" asp-action="Index">Schedule a Flight</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto d-flex flex-row">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="me-4">
                                <a asp-area="" asp-controller="Checkout" asp-action="Index" asp-route-user="@User.Identity.Name">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-cart2" viewBox="0 0 16 16">
                                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0" />
                                    </svg>
                                </a>
                            </li>
                            <li class="nav-link text-dark text-center mx-2 mx-lg-1 fw-bold me-4">Hello, @User.Identity.Name!</li>
                            <li class="nav-item text-center mx-2 mx-lg-1">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item text-center mx-2 mx-lg-1">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item text-center mx-2 mx-lg-1">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3" style="min-width: 250px; max-width: 1500px; margin: auto; padding-left: 40px; padding-right: 40px;">
        @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Evan Airlines - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>